apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:6XoVHdEZJ5qXvl505hiqajehbCVG6MwFdjYDsl/8VADM3XSa,iv:r/Etsn0SrlO+YvvX2DRBr1rXnb1BbbA69MNkh4+Pfg8=,tag:hq3BYD6V7rC2XfLEb54aZg==,type:str]
    credentials.json: ENC[AES256_GCM,data:XdXhPRz3otyblwiNxZI0kk36iposJHz8ozmrxKWGGZDeF8YiZUAtAZZb/IYyAQI6c3HV3VyIKyydgu6BgUST45c2XiKO8/HbWdCApe1LrrZVtVGDmxLPkQxxdul2y2BLOVKjcY7R9OTKK8IPx78KH5hmDjGuz36JrzmrmUeVhSKnimgwhsB6E/zCrr1EKq4FnAzzS1gbBwyiphCPQQolGdRrgu4XAXLzK+cEAwLMqQ==,iv:ZpSUyT9RocGwXK7KqNBB9/1TJ7jDPAbwM2iL4WXZeac=,tag:Psjs79pqfLU+wupJPJns9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aW5zV3c5K1QyblBXZWZ6
            UEJDYnVrOHkvZXk3TnFYd3o2YjBsNTB6VUNvCmR6NUkzL3BLcGM1NlRxNzlLbHF3
            Z0hZZFBFK3RQR1JaZFhjSDFxcEFEYkUKLS0tIEsrcnl4bU9MRldZM3pyZEpNcUkr
            cWJ0UWgwejRwd1V6THZ1VW9BRzRBSmMKpRbb0Noj9asUYRJauyFJ7jppEC51HNPH
            Uxvw0BHjgehIPppyv7CilYKE4eDjR1c2O8pxUoPTFPfWBdiExuCg5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T17:32:48Z"
    mac: ENC[AES256_GCM,data:NabDFgjtE6OPPpjC7o3MC/9VQIuYkr+C6zyKUi0O1/NGoQnJwd+2skfpVMAjKydoXRI9Ja9zEWHz1eP38klrQPMp6nnBIVxHzHRiePorl1BTv/n+19+lsL/oI1RFYWSAFyRMAEgpJyuRbPqtWJaGzBnQNeprZmWSN/FTwVBxgZE=,iv:rzaGYlkrR83csZYobOe6dY05Dmc71VhvJ5W6tYpc95g=,tag:03UN8zvChVSgYmERHzgqQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
