apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:5Edn3vULei0iQd76mfxmcGeg6lJJ1SWouTvDavp3XChGl0cK,iv:TRCypWiTju85S+FJbOjseHQsUiNaefmmRujIDMfE9Us=,tag:2RD6tbjGdWZgRnJ1qRZIrw==,type:str]
    credentials.json: ENC[AES256_GCM,data:VQmaeeX8e7eVqGwbfbEslJVUmzzegUbZ3hMou1IQ3nT9vhR0/CFGETiLiset7yBHm/aBdyMyAYyNukZK8PiIPFiHMLjtyKIApzvk7hc4yURFpUfWvtxtuMUxnMULqDdSk+yk7ODPiUAdouYB22ykuDCLH+IUOUvt+LK2/bnZI2i+aWhySsyAusBljOO87NZ24HPei0oWL/4MVzvgvQGgiDJ1P30wPGvqqz9MkBe0OQ==,iv:lv2nhyMoDSrDV1cd88nJACfBIeNp11faPDcJ6rJuHzY=,tag:ZIhbxrcVY02PPsqbCnhukg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SFNZU0UzNzdxSzRPNWxF
            N0pWajc3S2RPVTNXQ1NURXlRM0RLNXMrNEd3CktuZTJNc2o3bGdSY082QnVqQTBy
            V3lKMGVHRnhKOWNubjdxQXNOQmwza1EKLS0tIGZ2aXVWbEpUQ0txZjlsT3BFU0JO
            RnhNS1NudUpMRm5PZ1BpYTgzdnVSQVUKScCT1KiJwO7zdsTDOFRLT6TovNSYIwoN
            YmcRTzaWwMfjpl7+OaGh5YJbQpDjx9KiyVzQPctPuc0HnWSZJsFeFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T14:38:01Z"
    mac: ENC[AES256_GCM,data:qG5xe7Tp+4Mu1oR0P9rcd/UsQAkGiYr2w8YvGJM7SMshbOE9TFCbDaeG7Bd3Lsu5X/nor+sY+J8y2gT4FP4jc1hpDrK6+KkMvO39zgixpIra9lxqooK8BXxgWQ6pdq7w5uGY7aSPukZkdXYxeEgJszCBMiqsyhpH6WayXEQS9Do=,iv:i0Sg4hHZO4Tl2z9IZfKvjW30Rg+hljAUUuNSsf8WsOs=,tag:53wGp2Hn5sqwacL0f0YrVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
