apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:wPMsUYz8eWDBdLzkEKa0M/Fh/c6vRlP0uAd0iTx/n6+3YZ/4cnEQKg==,iv:duNK8Cyyt8eHr/lBK1Ustu1gVimuqcl3TA+pOzOVDfw=,tag:jj0YTV4Vr3uWSP7J+aIpYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL21CbWRBWDZmUityV1Jw
            OGV5Yms2OHQ3aUVNNjl1YS9MbEk5UXIvdDJZClpnT0JSenExZXVBSFNaRzhpcS9J
            YUtKZlI2VlZ5MGFHb054c00raGVyNlEKLS0tIEtEOUJUdnM3SXpXK2o1WXU5Wmtk
            T2VUT0VoVm15RGRBOVdJZUFEbExpOVEKN3VHVajyOJq8lLOBS8UQOC2P/HwpjMXn
            UO9o8BpMOXavrqJ4iKhMHwV1WrkhPj67Qqakg1Hs3l1UfxJS6Is/Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T15:43:27Z"
    mac: ENC[AES256_GCM,data:n8HAS0yvvtzoyON9MBUpQJDlrbgISduEcVjPfRh9QIzlm5vdYKNm2fBst6eBf6Gq4zeLYriH8AqLX5iHcQt6mwttqADLYHG10v+H/pPPzQPazVtvvLORC1ebOWfE8townJBzdHUzFNatq2eIGT8/08b4QHUOXohDfl+vjWUI6fg=,iv:ZDvRowSYj6XVYlqymcy+sjhvh3DKovTKpiyDa7ZONrQ=,tag:dx3xnwG53ytugaTuV8LY4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
