apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:v6O2kppfIQRED9vUeWeb/tGYPy1q9u3102igCJ66d9njfTTpgyKKkg==,iv:GFh6Cnni+/eET03IbBl28OxraSAKEhIVuF/VM9bkcPU=,tag:BqGENwynAVwuEOmNDPMvxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudW9jSUJWbWljeGVLVENo
            V0pUUG9ncHpwM0xzWnU3MFFxbEU5dStzcnh3ClNEMVJ6dHptZUNGNjJDRXlwTzVF
            Y3k5emlYY0JBNkNucTdlT0RWZkhPVmsKLS0tIHAyYnI3bXNZd3BXWjJnUG03ZUVD
            amYrVnRqZy8yV2lrdmVIdXpoK0VhdVUKjLC8a14nWwsm0nlXs50+XO8utNCF3fL7
            IhrGYMuUzmCQcWSowoEtlaITLA+qrDFBrDAsjyoQ3mBN6/IkUFNWcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T18:24:43Z"
    mac: ENC[AES256_GCM,data:AUbg/T8c1ryD7MkOBfpnXMgi4qBV++w6aKvCOHpQslyHpputmmSt0j2XL/ZXG+r85m/zhOqL2ba2ma4S2LMBJlC6P8vLNpdFlYgiaFrzXTWS7cv/9UZlH46dqjpWBvx260W5IaBwwZRxhTmmN7z4k8ZQQydhDu9yN44m/MWK7TY=,iv:DwHO3SH7cBUI0k3QZIog8O3z46BBrpq8vekJ66z74lE=,tag:kGBhwgdvjv94VNNYqJEz/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
