apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:8ipkMZT8EN9tUO50my99VzkTvSvCl8JZvSFDQ9xcZ/FbqkDgNonzWg==,iv:DRKGUsiQA1XQcQvKaqet7SI8qJfltjwrvdoD1GwZd4Y=,tag:lnjVOmHsTST2o6cFXO1BJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdFJpQk9UejJsSUVLc2RS
            eXZzaHMzY21zU0RWUFowT1cydjd1SHhWdUFNCnp3TkFFalBWTFFpRlV3U3RxbEJZ
            N3Eva05lajIwbFlzZVN2T2JVSDB2YkEKLS0tIDAvWlgyTkRNeUtiRUtLZHdlTTlG
            eEl6dGtqNElPTy9aQW9ZZVIzVVNoSGsKAsMov8qGUv/IiC7Rk26Iw6ixV/Py0OIW
            BrXDCiQSxlciOL63eVcRfts6Ipal2p2651t+KwFR8OkTm2SPKs8EGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T19:47:30Z"
    mac: ENC[AES256_GCM,data:synzeuUxT0YQPMOIQzyBFWncHN0HuePo/HCmWo/CPwoiJ+70Msl27uhuKny5yuLSKTcT8OVQa36IvlDTXzq+1cjDLMytH/ZTr4gMjJcfdK5SUXqKr6qbHr7un1JmCl/H9ie3QdupF3ylp89WlAYlHwPN9k0k3eqL+Qb/8KU7QTQ=,iv:+I/GGoheCcCwXTaZiV5Pv/nQbAKEAIZzOzMwa3fdqF8=,tag:oZnArRz+cp7DqfeCVK9NzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
