apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:eFGErRnBb5qeWt+rhO9qo5NkhNVu8q/Yds5uwe23pkcqjyX9FoF6dvmfiHSH0M/2VCeARUdP3hDNWz92A0YDhaAhBjT9e5RxHfTW1fhrivGNM1EgV5gPmhEqo10zhg==,iv:ItJwIS4Of06/p7keI7lrNYu9J0rwpAlT1unF+RcJehg=,tag:uQg1yndGfOCFoOkD8qdsVg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:za0hGd98A5h7wkHVwy9x,iv:ybT5aSwRqWRXoEi/pAP1CLbM6R39xR5TFxRQ3dCpryg=,tag:b4Q2pHZD7xoSnsE4Xsxc9w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:bLe7QWno5I5nRrfeJ2IvcfBTFG50,iv:5Hxk+N3+kpBqtSAX3OqcxVDgWw4wt8SgHnNZodvIH7Y=,tag:WhDpmQbleYNKxRq23KxZMQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:JRUYIc1BJNBfOGKf9v7sDXEl98Wm1rv2Gs9MmC0+E3m2V8am,iv:Kno0wwBBOfzZ7gQSkdNBYD2gEuiLZNhdLBvFmbxuneM=,tag:mRp2dNYaEqSvpzmgvcnc7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPT0ZNdlc3QkE5Q3RGUkQz
            OGx5b0RYL0xMWGJFTmhZbHFzbmJYNFN2endVCmF0QitORWdNcVJadjl6SVFudkpt
            Y0ppZEtBbXd6L2NGWU41WlpyRHJ6S28KLS0tIEpHR3FtZURld1R0cm9ya2hhQTRj
            QS9EOHVLd2h1a0xzbU9OL1p5YnlDNTgKmZ6Ohd6T7pZEiROO88MnJICVd9tiX344
            OXr8XxZfUxPX2y9G3POgdvNVNBHP1z6MnZeEVlMpVXopD7eqXwyCCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T18:24:43Z"
    mac: ENC[AES256_GCM,data:gZEgD5lgrlXTf+4+9nLStho9GH51bhxvognfDQ0kqt/O5bbtzn1xUdI+n6gB8pL+5tsDvCFfk1anSOd17mzX2qn12L+gi6ohLD6gc6NoQIludxV3zIjfeDfKMBIgun+PEdgSXjUFljMKXP89T1Zc+4bce/tV5TOhAKnm9x5ts8g=,iv:ZEtv2zSv5nalgiG9a8uAlrHqSSR/eu1SD3UchwDNUss=,tag:E14Vh9B4YTEbButdittEqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
