apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QnRBMUp2a0RJNjdRWWVG
            TENhNEtla0JOOThpUWN3clBIMVN1U0hzeEM0CnAydXpub3BtL3QwSlZvcDJGc3RW
            RHMvWkJwVDBuS1R6NzcwWHNIa09MeW8KLS0tIGJZdGl2RnM2S1p6UWFJeXhMT0Q3
            TThKZktvcUtuWWZMNjlWNWo5eTQ4TlEKnIhoqEHCKxCLWgUu8iIs96aZcogsDboj
            ynSlGhKtefC0IaYnXscTmVFyeOPy7SLfGN1/jPBxdKskGbo/NRGk+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T14:38:01Z"
    mac: ENC[AES256_GCM,data:Sa9cQ1BwmNLbSLUWWa4k058WeOy16os+Oc5FnjRTPr6dDVUMBmw0xv5/sELluCDRdGVGo+f6l0lxrTi2ZmEpC7wq60hLnijM0J/lQHGuoXTukMvN4LcFjOVFNbhj5n18rlI2EfHb8nJo9vhVWFbN6wvxGwChaxCY+D4wAskeQQU=,iv:IEcOgdPpfxkdhBgPcad0V0njw67/xZ86vbRGfiThJHg=,tag:f41ETnlNSvTJRsoAEQ0ZWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
