apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSXJVVHRCWmpXRitnd3dL
            NS8wL1RFT2ZFSWxXZWlqbTF2cDN1THZ6UVVjCm4zT2pHZjlNa0RlZ3R6SzlrUEVt
            TVZETnBDbUk2TjVGZk0rV3N1cDF6U0EKLS0tIGxMb2ZXRmx2V0xDYXlRNnFlcEx1
            TFlBWFAzQ2E0bUc2SEIrOVRGNWt5c3MKgESSdVYS/L9Cu270UN0Wmy1gNxcPC39R
            GLJIqh+asBSeLZm8Ao5LPTkC9T1iOLD01dquyQlB9wstYKoILWflUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T19:47:30Z"
    mac: ENC[AES256_GCM,data:V7rLkzqxFNIgXxe5jqi29IojAhOd1ONUCGelnpkyEXqrzJHSXt/YeVS/v9e2+n45jS3duJSY82YW5SUV2u+nNDf4M46mpJiWeTMG0SvloLU+uBj1imA6EWPHiUOG+yrmL9INQjgtZDmTqhOLr+Jday7/la5P12Zr5AfgEzrSRlU=,iv:M9Hz4wrCA2NCJjzqSwnfs8TWjuC4ZLy8aR2BIBVLrCo=,tag:My1DIgKnKgX0w8apBD+tqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
