apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:FszvVFgUN86fcTOAkCFFV4CASkW38P/se7M4hNwQhCmqxVEZ+fGinA==,iv:Uh923m6OatZlOZKQ1xJJmK8AOeRDuly8N19oV1D1/00=,tag:RbWRK2PV2zMCxMQkQLVNaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZXkzNjhaaHQyVmI2ak5r
            dTJvdldQN0tQbXdWVWV5ZXpFOWhrVnoxaGxFCm1QR3RMdjNyWi9zODN0bDRMYkk0
            V05qdFZYeWNuUkpoQSs3dUZMU3U1WUUKLS0tIGFvMm1uQ0p2YzkySFBYYzIzK3hT
            ZnVHRlE1ZlhzaDNOVDNIYzBaZzIxMkkKKDol4Xbuf2FhAz27cjGPILwFFClIyQ/c
            hZTtNQwVy90PZQhIGxneFk7sEHIxb3rz0qrZH50kkk6F23Ra7+MRzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T14:38:01Z"
    mac: ENC[AES256_GCM,data:hU4s+wHGd+G9UAk6fWbZfvoQrrNrn2g6DNXAi8FN6vI+gnQaXfZwoO3uwasOfZ4jLUx/zev19qFicA1QQhUL/c4zotfjzqfxOWpPaPGgsWJ6qgIn8wYx80b9iZXAvlmfitm/EI5Cq46FkaPPFIVVTSBtH+wpsRu7QlMz9FtzKJI=,iv:Fn/YsjscuRer2d7gMJ8rKLR8PP6FelRr2HO4AfRVwUI=,tag:1yKt91t2jWcQJXD6L8RPKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
