apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4CwrwLu2aOKalo7eTa/k2SBJcXMVqw06mNunVSlnrXaWBzsDt+MZHQ==,iv:wL6vFr8JaTSFvGxn9kUsYcTRVNnxQOK2ykfzpntNojs=,tag:2nVh7M1myl9LujzcJmeTTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON2VtWWVuWS96OW9JQlNR
            a3RnZWJMMndGdEtvbFZ5cDdybHFrODd0emdjCm91Q1hrUnFWVEhlWGpCb3RVZWpC
            VWNhaDlxRml5enU4SUhveDc3VDgrRW8KLS0tIExPdnJ5WWRibG5PVUs3SmRjMHhS
            TXNqeTVKSkJqM3JJWFVQWnhyUlY0M2MKmupOh6MB3z1/26GNX5U+nPKPfTAvmNj6
            wAlP3AockTZsbOEa0j10RM9Ht8f4czoK2oDNt8a5OIxtZ9iFgdVBvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T18:08:41Z"
    mac: ENC[AES256_GCM,data:f+T84js8T5MFlACC3prLvuNEE9dGGXeEuIORK/B8nNX5aGlitW3xUkIrXbaHWUeHUdQDEsAfEwzfSB8JvH1IXty0mYsEouzhf9tspJdGGwQlAJMae0WEVzuhJrxCl41GWV4cIRqM5AdM+hdK4SE025ZVCAVIc1IcHGo4YG3SfiY=,iv:jnHCQTMWI/Jvy7zpUuwa5iKlDVWM8e2QxzX3ZxxKKbk=,tag:ESoSEpPpZK8kH5sZWSDqKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
