apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:NxOyWoN4FjwaKJYbHQyKXIonFarXBPzfW5E1nhU+Bj/Fn2rS+3tdQw==,iv:Kztsv823FzGZsA5aDK6+8+dADxPj+GoSuZaVW5jwEBY=,tag:icIqk5UPMpKUEwY3r2eOaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTVdQRnFkMXRqb0ROdjdP
            ZTlJemJlTCswZEZiaEdvMXEwK3BkMUdqcmc4CnM3R0Rja21uSElUWGNXZGl3a1dk
            cXRmMktwUVlJZnJsNUUybTZmdjZCSHMKLS0tIDNwS2dYOEQ4WVVqWGpQMzJnQ2dF
            bDF2eFZCdEY4UnduN0xiaGZ2dWFvMEkKLEkm8CRgxoEYrgF/dich8dXl9Q7n9OI0
            kwn4POGQ+prw0SZhPnbBD8/wLRagO9zFVYgxlkNVdT8GnxFFqM1Y5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T20:03:38Z"
    mac: ENC[AES256_GCM,data:6cMo2dyly7hSoT1udOui5/aZ391OFol+E9plYkpf+iVy31VlOa85F4oTr7hQpLHATXKOxOKRjd/ObOwL2HlSnMzVCz4xpEhCaqEghvtiJMqamfDpB+MA7zP+q/f7AqsG8qRqhOxh/pT+6sWZPaRqdbg/IfKsVyC90cqb4MyOj/8=,iv:pwJZ8pI4/6XB22WeAKndxTJD5vVnSOG6DBAG7k18HMo=,tag:xu37z2HVNulNnZ67UWXrhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
